/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(project(":fe-common"))
    api(project(":plugin-common"))
    api(libs.io.netty.netty.handler)
    api(libs.com.google.code.gson.gson)
    api(libs.org.roaringbitmap.roaringbitmap)
    api(libs.com.google.guava.guava)
    testImplementation(libs.com.github.hazendaz.jmockit.jmockit)
    testImplementation(libs.junit.junit)
    compileOnly(libs.commons.codec.commons.codec)
    compileOnly(libs.org.apache.commons.commons.lang3)
    compileOnly(libs.org.apache.spark.spark.core.v2.v12)
    compileOnly(libs.org.apache.spark.spark.sql.v2.v12)
    compileOnly(libs.org.apache.hadoop.hadoop.common)
    compileOnly(libs.org.apache.parquet.parquet.column)
    compileOnly(libs.org.apache.parquet.parquet.hadoop)
    compileOnly(libs.org.apache.parquet.parquet.common)
    compileOnly(libs.commons.collections.commons.collections)
    compileOnly(libs.org.scala.lang.scala.library)
    compileOnly(libs.com.esotericsoftware.kryo.shaded)
    compileOnly(libs.org.apache.spark.spark.catalyst.v2.v12)
    compileOnly(libs.org.apache.logging.log4j.log4j.slf4j.impl)
}

description = "spark-dpp"
