/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(libs.com.google.guava.guava)
    api(libs.org.roaringbitmap.roaringbitmap)
    testImplementation(libs.junit.junit)
    testImplementation(libs.com.github.hazendaz.jmockit.jmockit)
}

description = "plugin-common"
