/*
 * This file was generated by the Gradle 'init' task.
 */

rootProject.name = "starrocks-fe"
include(":fe-core")
include(":fe-common")
include(":spark-dpp")
include(":plugin-common")
include(":hive-udf")
