/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(project(":plugin-common"))
    compileOnly(libs.io.trino.hive.hive.apache)
    compileOnly(libs.org.apache.hadoop.hadoop.client)
}

description = "hive-udf"
